python
"""Production‑grade CRUD module for the ``slits`` table.

Features
--------
* Typed Pydantic payload validation.
* Full type hints and comprehensive docstrings.
* Centralised logging with appropriate levels.
* Robust error handling (SQLAlchemyError, ValidationError, ValueError).
* Input validation and basic security checks.
* Performance‑aware query patterns (bulk insert, pagination).
* Clean‑code best practices (no magic numbers, explicit imports, immutable defaults).

Typical usage
-------------
>>> from slits import (
...     get_engine,
...     init_db,
...     session_scope,
...     create_slit,
...     get_slit,
...     update_slit,
...     delete_slit,
...     list_slits,
... )
>>> engine = get_engine("postgresql+psycopg2://user:pwd@host/db")
>>> init_db(engine)
>>> with session_scope(engine) as sess:
...     new = create_slit(sess, {"name": "A1", "length": 12.5, "width": 3.2})
...     fetched = get_slit(sess, new.id)
"""

from __future__ import annotations

import logging
from contextlib import contextmanager
from datetime import datetime
from typing import Any, Generator, List, Mapping, Optional, Sequence, Tuple

from pydantic import BaseModel, Field, ValidationError, validator
from sqlalchemy import (
    Column,
    DateTime,
    Float,
    Index,
    String,
    Text,
    create_engine,
    event,
    func,
    types,
)
from sqlalchemy.engine import Engine
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session, sessionmaker

# --------------------------------------------------------------------------- #
# Logging (configuration should be performed by the host application)
# --------------------------------------------------------------------------- #
logger = logging.getLogger(__name__)

# --------------------------------------------------------------------------- #
# Pydantic payload – validates incoming data before DB interaction
# --------------------------------------------------------------------------- #
class SlitPayload(BaseModel):
    """Schema for a Slit record.

    Attributes
    ----------
    id: Optional[str]
        UUID v4 primary key – generated by the DB if omitted.
    name: str
        Human‑readable name, max 100 characters, non‑empty after stripping.
    length: float
        Length in millimetres; must be > 0.
    width: float
        Width in millimetres; must be > 0.
    material: Optional[str]
        Optional material description, max 50 characters.
    description: Optional[str]
        Free‑form description.
    created_at: Optional[datetime]
        Set by the DB on insert – ignored on write.
    updated_at: Optional[datetime]
        Set by the DB on update – ignored on write.
    """

    id: Optional[str] = Field(default=None, description="UUID v4 primary key")
    name: str = Field(..., max_length=100, description="Readable name")
    length: float = Field(..., gt=0, description="Length in mm")
    width: float = Field(..., gt=0, description="Width in mm")
    material: Optional[str] = Field(
        default=None, max_length=50, description="Material description"
    )
    description: Optional[str] = Field(default=None, description="Free‑form text")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp")
    updated_at: Optional[datetime] = Field(default=None, description="Update timestamp")

    @validator("name")
    def _strip_name(cls, v: str) -> str:
        """Trim whitespace and ensure non‑empty after stripping."""
        stripped = v.strip()
        if not stripped:
            raise ValueError("name must not be empty or whitespace")
        return stripped

    @validator("material", "description", pre=True, always=True)
    def _normalise_optional_strings(cls, v: Optional[str]) -> Optional[str]:
        """Convert empty strings to ``None`` for consistency."""
        return v.strip() or None if isinstance(v, str) else v


# --------------------------------------------------------------------------- #
# SQLAlchemy declarative base and ORM model
# --------------------------------------------------------------------------- #
Base = declarative_base()


class Slit(Base):
    """SQLAlchemy ORM representation of a slits record."""

    __tablename__ = "slits"
    __table_args__ = (
        Index("ix_slits_name", "name", unique=False),
        {"mysql_engine": "InnoDB"},
    )

    id: str = Column(
        types.String(36),
        primary_key=True,
        nullable=False,
        server_default=func.uuid(),
        comment="Primary key – UUID v4",
    )
    name: str = Column(
        types.String(100),
        nullable=False,
        comment="Human‑readable name (max 100 characters)",
    )
    length: float = Column(
        Float,
        nullable=False,
        comment="Length in millimetres – must be positive",
    )
    width: float = Column(
        Float,
        nullable=False,
        comment="Width in millimetres – must be positive",
    )
    material: Optional[str] = Column(
        types.String(50),
        nullable=True,
        comment="Optional material description (max 50 characters)",
    )
    description: Optional[str] = Column(
        Text,
        nullable=True,
        comment="Optional free‑form description",
    )
    created_at: datetime = Column(
        DateTime,
        nullable=False,
        server_default=func.now(),
        comment="Timestamp added by DB on insert",
    )
    updated_at: datetime = Column(
        DateTime,
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
        comment="Timestamp added by DB on update",
    )

    @staticmethod
    def validate_payload(payload: Mapping[str, Any]) -> SlitPayload:
        """Validate a raw payload against the :class:`SlitPayload` schema.

        Parameters
        ----------
        payload:
            Mapping containing the raw data (e.g. ``request.json``).

        Returns
        -------
        SlitPayload
            A validated and normalised Pydantic model.

        Raises
        ------
        ValidationError
            If the payload does not satisfy the schema.
        """
        try:
            validated = SlitPayload(**payload)
            logger.debug("Payload validation succeeded", extra={"payload": payload})
            return validated
        except ValidationError as exc:
            logger.warning("Payload validation failed", extra={"errors": exc.errors()})
            raise

    @staticmethod
    def _before_insert(mapper, connection, target) -> None:  # pragma: no cover
        """SQLAlchemy event hook executed before an INSERT."""
        try:
            Slit.validate_payload(target.__dict__)  # type: ignore[arg-type]
            logger.info("Validated Slit before INSERT", extra={"id": target.id})
        except ValidationError as exc:
            logger.error(
                "Validation error before INSERT",
                extra={"id": getattr(target, "id", None), "errors": exc.errors()},
            )
            raise

    @staticmethod
    def _before_update(mapper, connection, target) -> None:  # pragma: no cover
        """SQLAlchemy event hook executed before an UPDATE."""
        try:
            Slit.validate_payload(target.__dict__)  # type: ignore[arg-type]
            logger.info("Validated Slit before UPDATE", extra={"id": target.id})
        except ValidationError as exc:
            logger.error(
                "Validation error before UPDATE",
                extra={"id": getattr(target, "id", None), "errors": exc.errors()},
            )
            raise


# Register event listeners for validation
event.listen(Slit, "before_insert", Slit._before_insert)
event.listen(Slit, "before_update", Slit._before_update)

# --------------------------------------------------------------------------- #
# Engine / session utilities
# --------------------------------------------------------------------------- #
def get_engine(database_url: str, **engine_kwargs: Any) -> Engine:
    """Create a SQLAlchemy engine.

    Parameters
    ----------
    database_url:
        SQLAlchemy database URL.
    engine_kwargs:
        Additional keyword arguments passed to :func:`create_engine`.

    Returns
    -------
    Engine
        Configured SQLAlchemy engine.

    Raises
    ------
    ValueError
        If ``database_url`` is empty or not a string.
    """
    if not isinstance(database_url, str) or not database_url.strip():
        raise ValueError("database_url must be a non‑empty string")
    engine = create_engine(database_url, future=True, **engine_kwargs)
    logger.info("SQLAlchemy engine created", extra={"url": database_url})
    return engine


def init_db(engine: Engine) -> None:
    """Create tables defined in the module if they do not exist.

    Parameters
    ----------
    engine:
        SQLAlchemy engine.

    Raises
    ------
    SQLAlchemyError
        If table creation fails.
    """
    try:
        Base.metadata.create_all(engine)
        logger.info("Database tables ensured")
    except SQLAlchemyError as exc:
        logger.exception("Failed to initialise database")
        raise


@contextmanager
def session_scope(engine: Engine) -> Generator[Session, None, None]:
    """Provide a transactional scope around a series of operations.

    Parameters
    ----------
    engine:
        SQLAlchemy engine.

    Yields
    ------
    Session
        SQLAlchemy session bound to the engine.
    """
    SessionLocal = sessionmaker(bind=engine, expire_on_commit=False, future=True)
    session = SessionLocal()
    try:
        yield session
        session.commit()
        logger.debug("Transaction committed")
    except Exception as exc:
        session.rollback()
        logger.exception("Transaction rolled back due to exception")
        raise
    finally:
        session.close()
        logger.debug("Session closed")


# --------------------------------------------------------------------------- #
# CRUD helpers
# --------------------------------------------------------------------------- #
def create_slit(session: Session, payload: Mapping[str, Any]) -> Slit:
    """Insert a new Slit record.

    Parameters
    ----------
    session:
        Active SQLAlchemy session.
    payload:
        Raw data to be validated and persisted.

    Returns
    -------
    Slit
        The persisted Slit instance.

    Raises
    ------
    ValidationError
        If payload validation fails.
    SQLAlchemyError
        If the INSERT operation fails.
    """
    validated = Slit.validate_payload(payload)
    slit = Slit(**validated.dict(exclude_unset=True))
    session.add(slit)
    try:
        session.flush()  # Populate PK and timestamps
        logger.info("Created Slit", extra={"id": slit.id})
        return slit
    except SQLAlchemyError as exc:
        logger.exception("Failed to create Slit")
        raise


def get_slit(session: Session, slit_id: str) -> Optional[Slit]:
    """Retrieve a Slit by primary key.

    Parameters
    ----------
    session:
        Active SQLAlchemy session.
    slit_id:
        UUID of the Slit.

    Returns
    -------
    Optional[Slit]
        The Slit instance if found, otherwise ``None``.
    """
    try:
        slit = session.get(Slit, slit_id)
        if slit:
            logger.debug("Fetched Slit", extra={"id": slit_id})
        else:
            logger.warning("Slit not found", extra={"id": slit_id})
        return slit
    except SQLAlchemyError as exc:
        logger.exception("Error fetching Slit")
        raise


def update_slit(
    session: Session,
    slit_id: str,
    payload: Mapping[str, Any],
) -> Slit:
    """Update an existing Slit record.

    Parameters
    ----------
    session:
        Active SQLAlchemy session.
    slit_id:
        UUID of the Slit to update.
    payload:
        Fields to update; will be validated against the schema.

    Returns
    -------
    Slit
        The updated Slit instance.

    Raises
    ------
    ValueError
        If the Slit does not exist.
    ValidationError
        If payload validation fails.
    SQLAlchemyError
        If the UPDATE operation fails.
    """
    slit = get_slit(session, slit_id)
    if slit is None:
        raise ValueError(f"Slit with id {slit_id!r} does not exist")

    validated = Slit.validate_payload(payload)
    for key, value in validated.dict(exclude_unset=True).items():
        setattr(slit, key, value)

    try:
        session.flush()
        logger.info("Updated Slit", extra={"id": slit_id})
        return slit
    except SQLAlchemyError as exc:
        logger.exception("Failed to update Slit")
        raise


def delete_slit(session: Session, slit_id: str) -> None:
    """Delete a Slit record.

    Parameters
    ----------
    session:
        Active SQLAlchemy session.
    slit_id:
        UUID of the Slit to delete.

    Raises
    ------
    ValueError
        If the Slit does not exist.
    SQLAlchemyError
        If the DELETE operation fails.
    """
    slit = get_slit(session, slit_id)
    if slit is None:
        raise ValueError(f"Slit with id {slit_id!r} does not exist")
    try:
        session.delete(slit)
        session.flush()
        logger.info("Deleted Slit", extra={"id": slit_id})
    except SQLAlchemyError as exc:
        logger.exception("Failed to delete Slit")
        raise


def list_slits(
    session: Session,
    *,
    offset: int = 0,
    limit: int = 100,
    order_by: Tuple[Any, ...] = (Slit.created_at.desc(),),
) -> List[Slit]:
    """Return a paginated list of Slits.

    Parameters
    ----------
    session:
        Active SQLAlchemy session.
    offset:
        Number of rows to skip.
    limit:
        Maximum number of rows to return.
    order_by:
        Columns to order the result set by.

    Returns
    -------
    List[Slit]
        List of Slit instances.

    Raises
    ------
    SQLAlchemyError
        If the query fails.
    """
    if offset < 0 or limit <= 0:
        raise ValueError("offset must be >= 0 and limit must be > 0")
    try:
        query = session.query(Slit).order_by(*order_by).offset(offset).limit(limit)
        results = query.all()
        logger.debug(
            "Listed Slits",
            extra={"offset": offset, "limit": limit, "count": len(results)},
        )
        return results
    except SQLAlchemyError as exc:
        logger.exception("Failed to list Slits")
        raise


def bulk_create_slits(
    session: Session,
    payloads: Sequence[Mapping[str, Any]],
) -> List[Slit]:
    """Insert many Slit records efficiently.

    Parameters
    ----------
    session:
        Active SQLAlchemy session.
    payloads:
        Iterable of raw payload dictionaries.

    Returns
    -------
    List[Slit]
        List of persisted Slit instances.

    Raises
    ------
    ValidationError
        If any payload fails validation.
    SQLAlchemyError
        If the bulk INSERT operation fails.
    """
    if not payloads:
        return []
    validated = [Slit.validate_payload(p).dict(exclude_unset=True) for p in payloads]
    slits = [Slit(**data) for data in validated]
    session.bulk_save_objects(slits)
    try:
        session.flush()
        logger.info("Bulk created Slits", extra={"count": len(slits)})
        return slits
    except SQLAlchemyError as exc:
        logger.exception("Failed bulk create Slits")
        raise


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #
__all__: List[str] = [
    "SlitPayload",
    "Slit",
    "get_engine",
    "init_db",
    "session_scope",
    "create_slit",
    "get_slit",
    "update_slit",
    "delete_slit",
    "list_slits",
    "bulk_create_slits",
]
