#undef ABSORB_NUTRITION_BARRIER
#undef NUTRITION_PER_DAMAGE
#undef NUTRITION_PER_KILL
#undef VORE_SOUND_VOLUME
#undef PREYLOOP_VOLUME
#undef TRAIT_SOURCE_VORE

#undef DIGEST_MODE_DRAIN
#undef DIGEST_MODE_HEAL

// CHOMPStation Shrink/Grow modes (issue #31, part 2)
#undef DIGEST_MODE_SHRINK
#undef DIGEST_MODE_GROW
#undef VORE_RESIZE_RATE_PER_SECOND
