/obj/machinery/vending/wardrobe/cent_wardrobe
	name = "\improper CentDrobe"
	desc = "A one-of-a-kind vending machine for all your centcom aesthetic needs!"
	icon_state = "centdrobe"
	product_ads = "Show those ERTs who's the most stylish in the briefing room!"
	vend_reply = "Thank you for using the CentDrobe!"
	products = list(
		/obj/item/clothing/glasses/sunglasses = 3,
		/obj/item/clothing/head/hats/centcom_cap = 3,
		/obj/item/clothing/head/hats/centhat = 3,
		/obj/item/clothing/head/hats/intern = 3,
		/obj/item/clothing/under/rank/centcom/commander = 3,
		/obj/item/clothing/under/rank/centcom/commander/skirt = 3,
		/obj/item/clothing/under/rank/centcom/intern = 3,
		/obj/item/clothing/under/rank/centcom/official = 3,
		/obj/item/clothing/under/rank/centcom/officer = 3,
		/obj/item/clothing/under/rank/centcom/officer/skirt = 3,
		/obj/item/clothing/suit/armor/centcom_formal = 3,
		/obj/item/clothing/suit/hooded/wintercoat/centcom = 3,
		/obj/item/clothing/shoes/laceup = 3,
		/obj/item/clothing/shoes/jackboots = 3,
		/obj/item/clothing/gloves/combat = 3,
		/obj/item/clothing/under/rank/centcom/ba_cheerleader/centcom = 3,
		/obj/item/clothing/gloves/ba_cheerleader/centcom = 3,
		/obj/item/clothing/shoes/sneakers/ba_cheerleader/centcom = 3,
	)

	zzplurt_product_categories = list(
		list(
			"name" = "High-Command",
			"icon" = "star",
			"products" = list(
				/obj/item/clothing/head/hats/centcom_cap = 3,
				/obj/item/clothing/head/hats/centhat = 3,
				/obj/item/clothing/head/beret/centcom_formal = 3,
				/obj/item/clothing/head/beret/centcom_officer = 3,
				/obj/item/clothing/under/rank/centcom/commander = 3,
				/obj/item/clothing/under/rank/centcom/commander/skirt = 3,
				/obj/item/clothing/under/rank/centcom/commander/turtleneck = 3,
				/obj/item/clothing/under/rank/centcom/commander/skirt/turtleneck = 3,
				/obj/item/clothing/under/rank/centcom/lieutenant = 3,
				/obj/item/clothing/under/rank/centcom/lieutenant/skirt = 3,
				/obj/item/clothing/under/rank/centcom/lieutenant/turtleneck = 3,
				/obj/item/clothing/under/rank/centcom/lieutenant/skirt/turtleneck = 3,
				/obj/item/clothing/under/rank/centcom/officer/senior = 3,
				/obj/item/clothing/under/rank/centcom/officer/skirt/senior = 3,
				/obj/item/clothing/suit/armor/centcom_commander = 3,
				/obj/item/clothing/suit/armor/centcom_jacket = 3,
				/obj/item/clothing/suit/armor/centcom_formal = 3,
				/obj/item/clothing/suit/space/officer = 3,
				/obj/item/clothing/suit/armor/vest/capcarapace/centcom = 3,
				/obj/item/clothing/suit/hooded/wintercoat/centcom = 3,
				/obj/item/clothing/glasses/sunglasses = 3,
				/obj/item/clothing/glasses/hud/civilian/sunglasses = 3,
				/obj/item/clothing/glasses/hud/security/sunglasses = 3,
				/obj/item/clothing/gloves/combat = 3,
				/obj/item/clothing/gloves/captain/centcom = 3,
				/obj/item/clothing/shoes/jackboots = 3,
				/obj/item/clothing/shoes/combat = 3,
				/obj/item/storage/belt/sheath/sabre/centcom = 3,
				/obj/item/storage/box/centcom_kit/spacesuit/command = 3,
				/obj/item/clothing/accessory/bubber/acc_medal/neckpin/centcom/executive = 3,
				/obj/item/clothing/mask/gas/atmos/centcom = 3,
				/obj/item/radio/headset/headset_cent/alt/with_key = 3,
			),
		),
		list(
			"name" = "General Staff",
			"icon" = "hat-cowboy",
			"products" = list(
				/obj/item/clothing/head/hats/intern = 3,
				/obj/item/clothing/head/utility/hardhat/white = 3,
				/obj/item/clothing/under/rank/centcom/official = 3,
				/obj/item/clothing/under/rank/centcom/official/turtleneck = 3,
				/obj/item/clothing/under/rank/centcom/officer = 3,
				/obj/item/clothing/under/rank/centcom/officer/skirt = 3,
				/obj/item/clothing/under/rank/centcom/intern = 3,
				/obj/item/clothing/suit/hazardvest/centcom = 3,
				/obj/item/clothing/gloves/color/black = 3,
				/obj/item/clothing/shoes/sneakers/black = 3,
				/obj/item/clothing/shoes/laceup = 3,
				/obj/item/storage/box/centcom_kit/spacesuit = 3,
				/obj/item/clothing/accessory/bubber/acc_medal/neckpin/centcom = 3,
				/obj/item/clothing/mask/gas/atmos/centcom = 3,
				/obj/item/radio/headset/headset_cent = 3,
				/obj/item/clothing/under/rank/centcom/ba_cheerleader/centcom = 3,
				/obj/item/clothing/gloves/ba_cheerleader/centcom = 3,
				/obj/item/clothing/shoes/sneakers/ba_cheerleader/centcom = 3,
				/obj/item/clothing/head/playbunnyears/centcom = 3,
				/obj/item/clothing/neck/tie/bunnytie/centcom/tied = 3,
				/obj/item/clothing/suit/jacket/tailcoat/centcom = 3,
				/obj/item/clothing/under/costume/playbunny/centcom = 3,
			),
		),
	)
	refill_canister = /obj/item/vending_refill/wardrobe/cent_wardrobe
	light_color = LIGHT_COLOR_GREEN
