/obj/machinery/vending/access/command/build_access_list(list/access_lists)
	access_lists["[ACCESS_CENT_GENERAL]"] = list( // NTC Rep stuff
		/obj/item/clothing/under/rank/nanotrasen/commander = 1,
		/obj/item/clothing/under/rank/nanotrasen/commander/skirt = 1,
		/obj/item/clothing/under/rank/nanotrasen/commander/turtleneck = 1,
		/obj/item/clothing/under/rank/nanotrasen/tactical/gold = 1,
		/obj/item/clothing/under/rank/nanotrasen/tactical/gold/skirt = 1,
		/obj/item/clothing/under/costume/playbunny/nanotrasen = 1,
		/obj/item/clothing/suit/jacket/tailcoat/nanotrasen = 1,
		/obj/item/clothing/head/beret/nanotrasen_formal/gold = 1,
		/obj/item/clothing/head/hats/nanotrasen_cap = 1,
		/obj/item/clothing/head/hats/nanotrasenhat = 1,
		/obj/item/clothing/head/hats/warden/drill/nanotrasen/nt = 1,
		/obj/item/clothing/neck/mantle/ntcmantle = 1,
		/obj/item/clothing/suit/armor/nanotrasen_formal = 1,
		/obj/item/clothing/suit/hooded/wintercoat/nanotrasen = 1,
		/obj/item/clothing/suit/space/officer/nanotrasen = 1,
		/obj/item/clothing/suit/armor/nanotrasen_greatcoat = 1,
		/obj/item/clothing/suit/armor/vest/nt_officerfake = 1,
		/obj/item/clothing/suit/armor/vest/capcarapace/nanotrasen = 1,
)
